# Generated by Django 5.2.7 on 2025-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': ('Запись блога',), 'verbose_name_plural': ('Записи блога',)},
        ),
    ]
